### ISSUE TITLE
Hit Callback não funcionando corretamente

### ISSUE THREAD

**Issue by BiancaK3** [DP6/analytics-helper#10]
A função atual é:

function() {
  return function(){
    analyticsHelper.internal._sentPageview = true;
    while(analyticsHelper.options.eventQueue.length){
      analyticsHelper.event.apply(analyticsHelper, analyticsHelper.options.eventQueue.shift());
    }
  };
}

E a função ajustada pelo Paulo é 

function() {
  return function(){
    analyticsHelper.internal._sentPageview = true;
    while(analyticsHelper.internal._eventQueue.length){
      analyticsHelper.event.apply(analyticsHelper, analyticsHelper.internal._eventQueue.shift());
    }
  };
}

**Comment by paulobrumatti** [comment]
Modificado e corrigido no commit https://github.com/DP6/analytics-helper/commit/d390934c89ec8f1839ba25055785ca8263d4183d, precisamos atualizar a documentação

**Comment by paulobrumatti** [comment]
Corrigido e normalizado para sem _.
