### ISSUE TITLE
Seletores baseados na tag body

### ISSUE THREAD

**Issue by BiancaK3** [DP6/analytics-helper#11]
Na documentação, não há uma especificação de como montar um seletor partindo de body, o que é indicado uma vez que algumas tags podem ser dinâmicas e apenas serem criadas depois da Janela Carregada, por exemplo.

Um exemplo de função se baseando no body seria:
  analyticsHelper.safeFn('Nome da Tag', function (helper){
    helper.on('change', '.seletor', function () {
     //sua função
    }, 'body');
  });

**Comment by paulobrumatti** [comment]
Voltamos o .delegate no commit https://github.com/DP6/analytics-helper/commit/d390934c89ec8f1839ba25055785ca8263d4183d, precisamos adicionar à documentação

**Comment by paulobrumatti** [comment]
Documentação sendo tratada no pull request abaixo:
https://github.com/DP6/analytics-helper/pull/26

**Comment by joaquimsn** [comment]
done!
