### ISSUE TITLE
Utilização de variável GA Settings

### ISSUE THREAD

**Issue by BiancaK3** [DP6/analytics-helper#12]
No container template, as Tags de UA Analytics possuem configurações do Google Analytics distintas. A melhor forma de configurar o GA no entanto, seria através da utilização de uma variável de configuração do GA chamada GA Settings.

**Comment by paulobrumatti** [comment]
Sendo resolvido neste pull request:
https://github.com/DP6/analytics-helper/pull/27

**Comment by joaquimsn** [comment]
!done
