### ISSUE TITLE
Helper sobrescrevendo propriedades internas

### ISSUE THREAD

**Issue by bpm1993** [DP6/analytics-helper#15]
### O problema:
Em alguns casos como quando o template de pageview e a tag de Helper rodam paralelamente, existe a possibilidade do disparo acontecer mais rápido que o carregamento do Helper, causando reset nas propriedades internas. O mesmo ocorre quando alguma tag coloca como dependência o Helper.

### A Solução:
A melhor solução é a validação se o helper já foi carregado. Só instanciando quando não houver sido instanciado anteriormente, além de colocar o helper como dependencia do template de pageview. Além disso é necessário configurar a tag do Helper como once per page.

#### Exemplo do código:
```javascript
function expose() {
  if (!window[options.helperName]) {
    window[options.helperName] = {
      internal: internal,
      init: init,
      pageview: pageview,
      event: event,
      sanitize: sanitize,
      getDataLayer: getDataLayer,
      cookie: cookie,
      getKey: getKey,
      safeFn: safeFn,
      fn: fn,
    };
  };
}
```

**Comment by paulobrumatti** [comment]
Podemos resolver isso utilizando a função "Once per page". Acho mais efetivo do que criarmos uma trava interna, pois o próprio GTM já fará essa limpeza para nós.

**Comment by paulobrumatti** [comment]
Resolvido com a adição do parâmetro "overwriteHelper", que vem desativada por padrão. Só pode ser ativada na função "init":

analyticsHelper.init({
  overwriteHelper: true
});
