### ISSUE TITLE
Erro ao passar um wrapper para um wrapper

### ISSUE THREAD

**Issue by Ibanheiz** [DP6/analytics-helper#5]
Precisamos fazer com que um wrapper que receba um novo wrapper simplesmente retorne ele mesmo.

**Comment by paulobrumatti** [comment]
Sendo tratado no PR abaixo:
https://github.com/DP6/analytics-helper/pull/28

**Comment by joaquimsn** [comment]
Done!

**Comment by joaquimsn** [comment]
Done!
