### ISSUE TITLE
Explicar como configurar o GTM

### ISSUE THREAD

**Issue by fmaruki-zz** [DP6/analytics-helper#8]
Existem algumas configurações que devem ser feitas no GTM para que a implementação funcione.

Por exemplo: é necessário configurar o hitcallback do pageview do GA para que a eventQueue funcione, isto não é mencionado na documentação atual.

O arquivo README-GTM-CONFIG.md está vazio, imagino que o objetivo dele seria explicar estes detalhes.

**Comment by paulobrumatti** [comment]
Explicado no commit abaixo (por você inclusive)
https://github.com/DP6/analytics-helper/commit/a02ae3687ca1c3d13187842ec868d4959bb37aad
